name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore: ["*.md"]
  pull_request:
    branches: [main]
    paths-ignore: ["*.md"]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, macos-14, windows-2025]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4

      # https://www.mongodb.com/docs/manual/tutorial/install-mongodb-enterprise-on-ubuntu-tarball/#prerequisites
      - if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt-get install libcurl4 libgssapi-krb5-2 libldap2 libwrap0 libsasl2-2 libsasl2-modules libsasl2-modules-gssapi-mit snmp openssl liblzma5

      # https://www.mongodb.com/docs/manual/tutorial/install-mongodb-enterprise-on-ubuntu-tarball/#prerequisites
      - if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get install libcurl4 libgssapi-krb5-2 libldap-2.5-0 libwrap0 libsasl2-2 libsasl2-modules libsasl2-modules-gssapi-mit snmp openssl liblzma5

      - if: matrix.os == 'ubuntu-24.04'
        run: ./build.ps1
        shell: pwsh
        env:
          NUGET_SOURCE: ${{ secrets.MYGET_SOURCE }}
          NUGET_API_KEY: ${{ secrets.MYGET_API_KEY }}

      - if: matrix.os != 'ubuntu-24.04'
        run: ./build.ps1
        shell: pwsh
