name: CI build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - run: ./build.ps1 --target=push --nuget-api-key=${{ secrets.myget_api_key }} --nuget-source=${{ secrets.myget_source }}
        shell: pwsh

      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: ./.output/**/*
