name: CI build

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore: ["*.md"]
  pull_request:
    branches: [main]
    paths-ignore: ["*.md"]

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4

      - run: ./build.ps1 --target=pack
        shell: pwsh

      - uses: actions/upload-artifact@v4
        with:
          name: output-${{ github.run_number }}-${{ github.run_attempt }}
          path: .output/
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
          include-hidden-files: true

  test:
    runs-on: ubuntu-latest
    needs: [pack]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4

      - uses: actions/download-artifact@v4
        with:
          name: output-${{ github.run_number }}-${{ github.run_attempt }}
          path: .output/

      - run: ./build.ps1 --target=test --exclusive
        shell: pwsh

  clean:
    if: always()
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: output-${{ github.run_number }}-${{ github.run_attempt }}