name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore: ["*.md"]
  pull_request:
    branches: [main]
    paths-ignore: ["*.md"]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4

      - if: matrix.os == 'ubuntu-latest'
        run: ./build.ps1
        shell: pwsh
        env:
          NUGET_SOURCE: ${{ secrets.MYGET_SOURCE }}
          NUGET_API_KEY: ${{ secrets.MYGET_API_KEY }}

      - if: matrix.os != 'ubuntu-latest'
        run: ./build.ps1
        shell: pwsh
