name: NuGet push

on:
  push:
    tags:
      - "*.*.*"

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - run: ./build.ps1 --target=pack
        shell: pwsh

      - uses: actions/upload-artifact@v3
        with:
          name: output-${{ github.run_number }}-${{ github.run_attempt }}
          path: .output/
          retention-days: 1

  test:
    runs-on: ${{ matrix.os }}
    needs: [pack]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x

      - uses: actions/download-artifact@v3
        with:
          name: output-${{ github.run_number }}-${{ github.run_attempt }}
          path: .output/

      - run: ./build.ps1 --target=test --exclusive
        shell: pwsh

  push:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - uses: actions/download-artifact@v3
        with:
          name: output-${{ github.run_number }}-${{ github.run_attempt }}
          path: .output/

      - run: ./build.ps1 --target=push --exclusive --nuget-api-key=${{ secrets.nuget_api_key }} --nuget-source=${{ secrets.nuget_source }}
        shell: pwsh

  clean:
    if: always()
    runs-on: ubuntu-latest
    needs: [push]
    steps:
      - uses: geekyeggo/delete-artifact@v2
        with:
          name: output-${{ github.run_number }}-${{ github.run_attempt }}
