name: Release

on:
  push:
    branches: ["main"]
    tags: ["*.*.*"]

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4

      # https://www.mongodb.com/docs/manual/tutorial/install-mongodb-enterprise-on-ubuntu-tarball/#prerequisites
      - run: |
          sudo apt-get install libcurl4 libgssapi-krb5-2 libldap-2.5-0 libwrap0 libsasl2-2 libsasl2-modules libsasl2-modules-gssapi-mit snmp openssl liblzma5

      - run: ./build.ps1
        shell: pwsh
        env:
          NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
